# Generated by Django 5.2.17 on 2026-10-02 22:32

import uuid

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Letter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("number", models.CharField(max_length=100, unique=True)),
                ("kind", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=180)),
                ("body", models.TextField()),
                ("template_revision", models.PositiveIntegerField(default=1)),
                ("pdf", models.BinaryField()),
                ("sha256", models.CharField(max_length=64)),
                ("signed_pdf", models.BinaryField(null=True)),
                (
                    "signature_status",
                    models.CharField(default="UNSIGNED", max_length=20),
                ),
                ("ezd_id", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LetterTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=180)),
                ("body", models.TextField()),
                ("revision", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="RateBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("start", models.DateTimeField()),
                ("count", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined"),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrator"),
                            ("COUNTY", "Urzędnik powiatowy"),
                            ("MAIN", "Urzędnik UMP"),
                        ],
                        default="COUNTY",
                        max_length=8,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="IntegrationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("provider", models.CharField(max_length=20)),
                ("operation", models.CharField(default="SEND", max_length=30)),
                ("key", models.CharField(max_length=100, unique=True)),
                ("status", models.CharField(default="QUEUED", max_length=20)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("remote_id", models.CharField(blank=True, max_length=180)),
                ("error", models.TextField(blank=True)),
                ("result", models.JSONField(default=dict)),
                ("next_attempt_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "letter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jobs",
                        to="registry.letter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoginCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("digest", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Office",
            fields=[
                ("id", models.SlugField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=180)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("MAIN", "Urząd główny"),
                            ("COUNTY", "Starostwo"),
                            ("CITY", "Miasto"),
                        ],
                        max_length=8,
                    ),
                ),
                ("city", models.CharField(max_length=80)),
                ("teryt", models.CharField(blank=True, max_length=7)),
                ("ade", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("allowed_domains", models.JSONField(default=list)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "MAIN")),
                        fields=("kind",),
                        name="one_main_office",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="letter",
            name="office",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="registry.office"),
        ),
        migrations.AddField(
            model_name="letter",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="received_letters",
                to="registry.office",
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("object_type", models.CharField(max_length=40)),
                ("object_id", models.CharField(max_length=100)),
                ("before", models.JSONField(default=dict)),
                ("after", models.JSONField(default=dict)),
                ("reason", models.TextField(blank=True)),
                ("ip", models.GenericIPAddressField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="registry.office",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="office",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="registry.office",
            ),
        ),
        migrations.CreateModel(
            name="PlateRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("number", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RESERVED", "Zarezerwowany"),
                            ("SENT", "Wniosek w toku"),
                            ("ALLOCATED", "Przydzielony"),
                            ("ISSUED", "Wydany"),
                            ("SOLD", "Pojazd zbyty"),
                            ("RELEASED", "Zwolniony"),
                        ],
                        default="RESERVED",
                        max_length=12,
                    ),
                ),
                ("owner", models.CharField(max_length=180)),
                ("address", models.CharField(blank=True, max_length=300)),
                ("vin", models.CharField(blank=True, max_length=17)),
                ("make", models.CharField(blank=True, max_length=80)),
                ("model", models.CharField(blank=True, max_length=80)),
                ("registration_date", models.DateField(blank=True, null=True)),
                ("sale_date", models.DateField(blank=True, null=True)),
                ("buyer", models.CharField(blank=True, max_length=180)),
                ("allocated_at", models.DateTimeField(blank=True, null=True)),
                ("reservation_until", models.DateTimeField(blank=True, null=True)),
                ("letter_number", models.CharField(blank=True, max_length=100)),
                ("note", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="registry.office",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Pool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("II", "Pula tablic zmniejszonych"),
                            ("III", "Pula tablic do badań"),
                        ],
                        max_length=3,
                    ),
                ),
                ("prefix", models.CharField(default="P", max_length=2)),
                ("scheme", models.CharField(default="NUMERIC", max_length=20)),
                ("start", models.PositiveIntegerField()),
                ("end", models.PositiveIntegerField()),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("station", models.CharField(blank=True, max_length=180)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="registry.office",
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "start"],
            },
        ),
        migrations.AddField(
            model_name="letter",
            name="pool",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="letters",
                to="registry.pool",
            ),
        ),
        migrations.CreateModel(
            name="PoolSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=12, unique=True)),
                ("ordinal", models.PositiveIntegerField()),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("case_number", models.CharField(blank=True, max_length=100)),
                (
                    "issued_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="slots",
                        to="registry.pool",
                    ),
                ),
            ],
            options={
                "ordering": ["ordinal"],
            },
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("I", "Tablica indywidualna"),
                            ("II", "Pula tablic zmniejszonych"),
                            ("III", "Pula tablic do badań"),
                        ],
                        max_length=3,
                    ),
                ),
                ("case_number", models.CharField(max_length=100)),
                ("count", models.PositiveIntegerField(default=1)),
                ("station", models.CharField(blank=True, max_length=180)),
                ("justification", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Szkic"),
                            ("SENT", "Oczekuje na decyzję"),
                            ("APPROVED", "Zaakceptowany"),
                            ("REJECTED", "Odrzucony"),
                            ("WITHDRAWN", "Wycofany"),
                            ("EXPIRED", "Rezerwacja wygasła"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authored_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decided_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="registry.office",
                    ),
                ),
                (
                    "record",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="registry.platerecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="pool",
            name="request",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="registry.request",
            ),
        ),
        migrations.AddField(
            model_name="letter",
            name="request",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="letters",
                to="registry.request",
            ),
        ),
        migrations.CreateModel(
            name="DeliveryEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remote_id", models.CharField(max_length=180)),
                ("kind", models.CharField(max_length=40)),
                ("content", models.BinaryField()),
                ("sha256", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence",
                        to="registry.integrationjob",
                    ),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("job", "remote_id"), name="unique_evidence")],
            },
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("office__isnull", True), ("role", "ADMIN")),
                    models.Q(("office__isnull", False), ("role__in", ["MAIN", "COUNTY"])),
                    _connector="OR",
                ),
                name="account_office_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="platerecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "RELEASED"), _negated=True),
                fields=("number",),
                name="unique_active_plate",
            ),
        ),
        migrations.AddConstraint(
            model_name="pool",
            constraint=models.CheckConstraint(
                condition=models.Q(("end__gte", models.F("start"))), name="pool_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="pool",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_until__isnull", True),
                    ("valid_until__gte", models.F("valid_from")),
                    _connector="OR",
                ),
                name="pool_dates",
            ),
        ),
    ]
