# Generated by Django 5.2.17 on 2026-10-02 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationjob',
            name='claimed_until',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='integrationjob',
            name='payload',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='integrationjob',
            name='payload_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='EZDCaseLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_id', models.UUIDField()),
                ('scope_kind', models.CharField(choices=[('REQUEST', 'Wniosek'), ('POOL', 'Pula')], max_length=8)),
                ('remote_id', models.CharField(blank=True, max_length=180)),
                ('remote_symbol', models.CharField(blank=True, max_length=180)),
                ('state', models.CharField(default='UNLINKED', max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('year', models.PositiveIntegerField()),
                ('number', models.PositiveIntegerField(null=True)),
                ('target_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registry.office')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('office', 'scope_id'), name='ezd_case_per_office_scope')],
            },
        ),
    ]
