# Generated by Django 5.2.17 on 2026-10-02 23:21

import hashlib

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_legacy_signatures(apps, schema_editor):
    Letter = apps.get_model("registry", "Letter")
    for letter in (
        Letter.objects.using(schema_editor.connection.alias).filter(signed_pdf__isnull=False).iterator()
    ):
        letter.signed_sha256 = hashlib.sha256(bytes(letter.signed_pdf)).hexdigest()
        # Suma archiwalnego pliku nie jest dowodem poprawności jego podpisu.
        letter.signature_status = "UNVERIFIED"
        letter.save(update_fields=["signed_sha256", "signature_status"])


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0002_integrationjob_claimed_until_integrationjob_payload_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="letter",
            name="signature_report",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="letter",
            name="signed_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="letter",
            name="signed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="signed_letters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="letter",
            name="signed_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RunPython(preserve_legacy_signatures, migrations.RunPython.noop),
    ]
