# Generated by Django 5.2.17 on 2026-10-02 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0003_letter_signature_report_letter_signed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="letter",
            name="replaces",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="versions",
                to="registry.letter",
            ),
        ),
    ]
