# Generated by Django 5.2.17 on 2026-10-02 23:38

from django.db import migrations, models


def preserve_references(apps, schema_editor):
    Request = apps.get_model("registry", "Request")
    NumberSequence = apps.get_model("registry", "NumberSequence")
    alias = schema_editor.connection.alias
    maximums = {}
    for request in Request.objects.using(alias).all().iterator():
        # Dokładnie dotychczasowe reference: rok UTC z created_at i PK.
        # Nie przepisujemy tekstu żadnego PDF ani znaków spraw urzędowych.
        year, ordinal = request.created_at.year, request.pk
        request.reference_number = f"W/{year}/{ordinal:05d}"
        request.reference_year = year
        request.reference_ordinal = ordinal
        request.save(update_fields=["reference_number", "reference_year", "reference_ordinal"])
        maximums[year] = max(maximums.get(year, 0), ordinal)
    for year, value in maximums.items():
        NumberSequence.objects.using(alias).update_or_create(
            scope="REQUEST", year=year, defaults={"last_value": value}
        )


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0004_letter_replaces"),
    ]

    operations = [
        migrations.CreateModel(
            name="NumberSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("scope", models.CharField(max_length=100)),
                ("year", models.PositiveSmallIntegerField()),
                ("last_value", models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="letter",
            name="number_ordinal",
            field=models.PositiveBigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="letter",
            name="number_year",
            field=models.PositiveSmallIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="reference_number",
            field=models.CharField(editable=False, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="request",
            name="reference_ordinal",
            field=models.PositiveBigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="reference_year",
            field=models.PositiveSmallIntegerField(editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name="letter",
            constraint=models.UniqueConstraint(
                fields=("office", "number_year", "number_ordinal"), name="unique_letter_ordinal"
            ),
        ),
        migrations.AddConstraint(
            model_name="letter",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("number_ordinal__isnull", True), ("number_year__isnull", True)),
                    models.Q(
                        ("number_ordinal__gt", 0),
                        ("number_ordinal__isnull", False),
                        ("number_year__gte", 1),
                        ("number_year__isnull", False),
                        ("number_year__lte", 9999),
                    ),
                    _connector="OR",
                ),
                name="letter_number_parts",
            ),
        ),
        migrations.AddConstraint(
            model_name="request",
            constraint=models.UniqueConstraint(
                fields=("reference_year", "reference_ordinal"), name="unique_request_ordinal"
            ),
        ),
        migrations.AddConstraint(
            model_name="request",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("reference_ordinal__isnull", True), ("reference_year__isnull", True)),
                    models.Q(
                        ("reference_ordinal__gt", 0),
                        ("reference_ordinal__isnull", False),
                        ("reference_year__gte", 1),
                        ("reference_year__isnull", False),
                        ("reference_year__lte", 9999),
                    ),
                    _connector="OR",
                ),
                name="request_number_parts",
            ),
        ),
        migrations.AddConstraint(
            model_name="numbersequence",
            constraint=models.UniqueConstraint(fields=("scope", "year"), name="unique_number_sequence"),
        ),
        migrations.AddConstraint(
            model_name="numbersequence",
            constraint=models.CheckConstraint(
                condition=models.Q(("year__gte", 1), ("year__lte", 9999)), name="sequence_year_range"
            ),
        ),
        migrations.RunPython(preserve_references, migrations.RunPython.noop),
    ]
