# Generated by Django 5.2.17 on 2026-10-03 00:34

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_numbersequence_letter_number_ordinal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('binding', models.CharField(max_length=64)),
                ('challenge', models.JSONField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
