# Generated by Django 5.2.17 on 2026-10-03 01:10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0006_public_challenge"),
    ]

    operations = [
        migrations.CreateModel(
            name="EZDIncomingDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("target_hash", models.CharField(max_length=64)),
                ("rpw_number", models.PositiveIntegerField()),
                ("rpw_year", models.PositiveSmallIntegerField()),
                ("document_id", models.CharField(max_length=180)),
                ("version_id", models.CharField(max_length=180)),
                ("workspace_id", models.CharField(max_length=180)),
                ("sha256", models.CharField(max_length=64)),
                ("content", models.BinaryField(null=True)),
                ("status", models.CharField(default="UNMATCHED", max_length=20)),
                ("error", models.CharField(blank=True, max_length=300)),
                ("request_url", models.CharField(blank=True, max_length=1000)),
                ("link_status", models.CharField(default="NOT_PUBLISHED", max_length=20)),
                ("link_error", models.CharField(blank=True, max_length=300)),
                ("link_attempts", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "letter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ezd_incoming",
                        to="registry.letter",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="registry.office"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "office",
                            "target_hash",
                            "rpw_number",
                            "rpw_year",
                            "document_id",
                            "version_id",
                        ),
                        name="unique_ezd_incoming_version",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("rpw_number__gt", 0), ("rpw_year__gte", 2000), ("rpw_year__lte", 9999)
                        ),
                        name="ezd_incoming_rpw_parts",
                    ),
                ],
            },
        ),
    ]
