# Generated by Django 5.2.17 on 2026-10-03 03:25

from django.db import migrations, models


def check_existing_periods(apps, schema_editor):
    pool = apps.get_model("registry", "Pool")
    missing = pool.objects.using(schema_editor.connection.alias).filter(kind="III", valid_until__isnull=True)
    if missing.exists():
        identifiers = ", ".join(str(value) for value in missing.values_list("uuid", flat=True)[:5])
        raise RuntimeError(
            f"Migracja wstrzymana: {missing.count()} pul modułu III bez terminu końca. "
            f"Przykładowe identyfikatory: {identifiers}. "
            "Ustal i zapisz terminy na podstawie dokumentacji urzędu, następnie ponów migrację. "
            "Nie przypisano automatycznie dat i nie usunięto danych."
        )


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0008_refresh_builtin_templates"),
    ]

    operations = [
        migrations.RunPython(check_existing_periods, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="pool",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "III"), _negated=True), ("valid_until__isnull", False), _connector="OR"
                ),
                name="pool_iii_finite_period",
            ),
        ),
    ]
