# Generated by Django 5.2.17 on 2026-10-03 04:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0009_require_finite_module_three_period"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("account_context", models.JSONField()),
                ("subject", models.CharField(max_length=180)),
                ("body", models.TextField()),
                ("content_sha256", models.CharField(max_length=64)),
                ("status", models.CharField(default="QUEUED", max_length=24)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("claimed_until", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("status__in", ["QUEUED", "SENDING", "REVIEW_REQUIRED", "CONFIG_ERROR"])
                        ),
                        fields=("user",),
                        name="one_pending_account_invitation",
                    )
                ],
            },
        ),
    ]
