# Generated by Django 5.2.17 on 2026-10-03 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0010_account_invitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlaggedWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("word", models.CharField(max_length=5, unique=True)),
                ("note", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["word"],
            },
        ),
        migrations.AddField(
            model_name="letter",
            name="posted_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="letter",
            name="posted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="posted_letters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="letter",
            name="posted_reference",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="platerecord",
            name="reminded_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pool",
            name="alerted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
