# Generated by Django 5.2.17 on 2026-10-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0011_workflow_improvements"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="removed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
