# Generated by Django 5.2.17 on 2026-10-05 20:07

from django.db import migrations, models

# Usługa jest pomocnicza i nie wydaje decyzji administracyjnych, dlatego wzór pisma
# nie używa sformułowania „Uzasadnienie decyzji”. Zamrożone wzory; nie importuj żywego kodu.
APPROVAL_TITLE = "Potwierdzenie możliwości wydania tablic indywidualnych"
PREVIOUS_BODY = (
    "W odpowiedzi na wniosek ${reference}, znak sprawy ${case_number}, potwierdzamy możliwość wydania "
    "tablic ${subject}.\nWnioskodawca: ${owner}\nUzasadnienie decyzji: ${reason}"
)
NEUTRAL_BODY = (
    "W odpowiedzi na wniosek ${reference}, znak sprawy ${case_number}, potwierdzamy możliwość wydania "
    "tablic ${subject}.\nWnioskodawca: ${owner}\nUzasadnienie: ${reason}"
)


def swap(apps, old_body, new_body, step, action, reason):
    Template = apps.get_model("registry", "LetterTemplate")
    Audit = apps.get_model("registry", "AuditLog")
    # Zmieniamy tylko niezmieniony wzór systemowy; własny wzór urzędu zostaje bez zmian.
    for row in Template.objects.filter(kind="APPROVAL", title=APPROVAL_TITLE, body=old_body):
        revision = max(1, row.revision + step)
        if Template.objects.filter(pk=row.pk, body=old_body).update(body=new_body, revision=revision):
            Audit.objects.create(
                action=action,
                object_type="LetterTemplate",
                object_id=str(row.pk),
                before={"title": row.title, "body": old_body, "revision": row.revision},
                after={"title": row.title, "body": new_body, "revision": revision},
                reason=reason,
            )


def update_defaults(apps, schema_editor):
    swap(
        apps,
        PREVIOUS_BODY,
        NEUTRAL_BODY,
        1,
        "template.default.updated",
        "Neutralne sformułowanie w niezmienionym wzorze systemowym; archiwalne pisma pozostają zachowane.",
    )


def restore_defaults(apps, schema_editor):
    swap(
        apps,
        NEUTRAL_BODY,
        PREVIOUS_BODY,
        -1,
        "template.default.restored",
        "Cofnięcie niezmienionego wzoru systemowego; archiwalne pisma pozostają zachowane.",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0013_demo_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Szkic"),
                    ("SENT", "Oczekuje na rozpatrzenie"),
                    ("APPROVED", "Zaakceptowany"),
                    ("REJECTED", "Odrzucony"),
                    ("WITHDRAWN", "Wycofany"),
                    ("EXPIRED", "Rezerwacja wygasła"),
                ],
                default="DRAFT",
                max_length=12,
            ),
        ),
        migrations.RunPython(update_defaults, restore_defaults),
    ]
